#
# Simply build and test by https://travis-ci.org
#
language: java

jdk:
- openjdk8

before_install:
- chmod +x gradlew

script:
- ./gradlew clean buildDist -x :asp-integrationtest:test
- ./gradlew fullintegrationtest

