
    Caller -> AspClientProgressMonitor: creates 
    Caller -> AspClient :calls with command and monitor object
    AspClient -> AspClientAction :creates 
    AspClient --> AspProgressMonitorSurveillance :registers client action for inspection 
    AspClientAction <-- AspClientProgressMonitorSurveillance : inspects progress monitor of client call
    AspClient -> AspClientAction :executes
    AspClientAction <-> AspServer :communicates with server per TCP/IP
    Caller --> AspClientProgressMonitor: changes to state "canceled" in progress monitor 
    AspClientProgressMonitor <--AspClientProgressMonitorSurveillance
    AspClientAction <-- AspClientProgressMonitorSurveillance : terminates socket connection on client call when progress monitor is canceled
    AspClient <- AspClientAction : returns response 
